name: .NET Core Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master , develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'
      
      - name: Restore dependencies
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Test
        run: |
          dotnet test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker image
        run: |
          docker build -t webshopback:dev .
          docker tag webshopback:dev aaa9758/dockerpractice:latest
          docker push aaa9758/dockerpractice:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
